// <auto-generated />
using System;
using MVCLab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCLab.Migrations
{
    [DbContext(typeof(context))]
    partial class contextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCLab.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("minDegree")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Degree = 90,
                            DepartmentID = 1,
                            Hours = 40,
                            IsDeleted = false,
                            Name = "C#",
                            minDegree = 0
                        },
                        new
                        {
                            ID = 2,
                            Degree = 85,
                            DepartmentID = 2,
                            Hours = 35,
                            IsDeleted = false,
                            Name = "Java",
                            minDegree = 0
                        },
                        new
                        {
                            ID = 3,
                            Degree = 88,
                            DepartmentID = 3,
                            Hours = 45,
                            IsDeleted = false,
                            Name = "Python",
                            minDegree = 0
                        },
                        new
                        {
                            ID = 4,
                            Degree = 92,
                            DepartmentID = 4,
                            Hours = 30,
                            IsDeleted = false,
                            Name = "Marketing Strategies",
                            minDegree = 0
                        });
                });

            modelBuilder.Entity("MVCLab.Models.CrsResult", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int?>("TraineeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.HasIndex("TraineeID");

                    b.ToTable("CrsResult");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CourseID = 1,
                            Degree = 60,
                            TraineeID = 1
                        },
                        new
                        {
                            ID = 2,
                            CourseID = 2,
                            Degree = 75,
                            TraineeID = 2
                        },
                        new
                        {
                            ID = 3,
                            CourseID = 3,
                            Degree = 80,
                            TraineeID = 3
                        },
                        new
                        {
                            ID = 4,
                            CourseID = 4,
                            Degree = 85,
                            TraineeID = 4
                        });
                });

            modelBuilder.Entity("MVCLab.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ManagerName = "Ayman",
                            Name = "SD",
                            isDeleted = false
                        },
                        new
                        {
                            ID = 2,
                            ManagerName = "Sara",
                            Name = "HR",
                            isDeleted = false
                        },
                        new
                        {
                            ID = 3,
                            ManagerName = "Ahmed",
                            Name = "Finance",
                            isDeleted = false
                        },
                        new
                        {
                            ID = 4,
                            ManagerName = "Layla",
                            Name = "Marketing",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("MVCLab.Models.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int?>("courseID")
                        .HasColumnType("int");

                    b.Property<int?>("departmentID")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("courseID");

                    b.HasIndex("departmentID");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Address1",
                            Image = "m.png",
                            Name = "Ahmed",
                            Salary = 0,
                            courseID = 2,
                            departmentID = 1,
                            isDeleted = false
                        },
                        new
                        {
                            ID = 2,
                            Address = "Address2",
                            Image = "female.png",
                            Name = "Fatima",
                            Salary = 0,
                            courseID = 3,
                            departmentID = 2,
                            isDeleted = false
                        },
                        new
                        {
                            ID = 3,
                            Address = "Address3",
                            Image = "male.png",
                            Name = "Omar",
                            Salary = 0,
                            courseID = 4,
                            departmentID = 3,
                            isDeleted = false
                        },
                        new
                        {
                            ID = 4,
                            Address = "Address4",
                            Image = "2.jpg",
                            Name = "Lina",
                            Salary = 0,
                            courseID = 1,
                            departmentID = 4,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("MVCLab.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("departmentID")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("departmentID");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Alex",
                            Grade = 95,
                            Image = "female.png",
                            Name = "Mariam",
                            departmentID = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Cairo",
                            Grade = 85,
                            Image = "male.png",
                            Name = "Karim",
                            departmentID = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Giza",
                            Grade = 75,
                            Image = "female.png",
                            Name = "Nour",
                            departmentID = 3,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Adress = "Luxor",
                            Grade = 80,
                            Image = "male.png",
                            Name = "Tamer",
                            departmentID = 4,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("MVCLab.Models.Course", b =>
                {
                    b.HasOne("MVCLab.Models.Department", "department")
                        .WithMany("courses")
                        .HasForeignKey("DepartmentID");

                    b.Navigation("department");
                });

            modelBuilder.Entity("MVCLab.Models.CrsResult", b =>
                {
                    b.HasOne("MVCLab.Models.Course", "course")
                        .WithMany("courseResults")
                        .HasForeignKey("CourseID");

                    b.HasOne("MVCLab.Models.Trainee", "trainee")
                        .WithMany("courseResults")
                        .HasForeignKey("TraineeID");

                    b.Navigation("course");

                    b.Navigation("trainee");
                });

            modelBuilder.Entity("MVCLab.Models.Instructor", b =>
                {
                    b.HasOne("MVCLab.Models.Course", "course")
                        .WithMany("instructors")
                        .HasForeignKey("courseID");

                    b.HasOne("MVCLab.Models.Department", "department")
                        .WithMany("instructors")
                        .HasForeignKey("departmentID");

                    b.Navigation("course");

                    b.Navigation("department");
                });

            modelBuilder.Entity("MVCLab.Models.Trainee", b =>
                {
                    b.HasOne("MVCLab.Models.Department", "department")
                        .WithMany("trainees")
                        .HasForeignKey("departmentID");

                    b.Navigation("department");
                });

            modelBuilder.Entity("MVCLab.Models.Course", b =>
                {
                    b.Navigation("courseResults");

                    b.Navigation("instructors");
                });

            modelBuilder.Entity("MVCLab.Models.Department", b =>
                {
                    b.Navigation("courses");

                    b.Navigation("instructors");

                    b.Navigation("trainees");
                });

            modelBuilder.Entity("MVCLab.Models.Trainee", b =>
                {
                    b.Navigation("courseResults");
                });
#pragma warning restore 612, 618
        }
    }
}
